name: Environment Creation Pipeline - $(Build.DefinitionName) - $(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

trigger: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  - template: ../recipes/common/Variables.yml

stages:
  - stage: CreateEnvironment
    displayName: "Create the Environment"
    jobs:
      - job: CreateEnvironmentJob
        steps:
          - task: AzureResourceGroupDeployment@2
            displayName: 'Deploy MLOps resources to Azure'
            inputs:
              azureSubscription: '${{ variables.RM_SERVICE_CONNECTION }}'
              action: 'Create Or Update Resource Group'
              resourceGroupName: '${{ variables.RESOURCE_GROUP }}'
              location: '${{ variables.LOCATION }}'
              templateLocation: 'Linked artifact'
              csmFile: '$(Build.SourcesDirectory)/mlops/recipes/setup/IaCAzureResourceManager.json'
              overrideParameters: '-workspaceName ${{ variables.WORKSPACE }} -storageAccountName ${{ variables.STORAGE_ACCOUNT }} -keyVaultName ${{ variables.KEY_VAULT }} -applicationInsightsName ${{ variables.APP_INSIGHTS }} -location ${{ variables.LOCATION }} -containerRegistryName ${{ variables.ACR }}'
              deploymentMode: 'Incremental'

  - stage: ProvisionCompute
    displayName: "Create Azure ML compute & AKS clusters"
    jobs:
      # Provision Azure ML compute cluster
      - template: ../recipes/setup/ProvisionAMLComputeCluster.yml
        parameters:
          rm_service_connection: '${{ variables.RM_SERVICE_CONNECTION }}'
          workspace: '${{ variables.WORKSPACE }}'
          resource_group: '${{ variables.RESOURCE_GROUP }}'
          aml_compute_sku: '${{ variables.AML_COMPUTE_SKU }}'
          aml_compute_cluster: '${{ variables.AML_COMPUTE_CLUSTER }}'

      # Provision AKS cluster
      - template: ../recipes/setup/ProvisionAKSCluster.yml
        parameters:
          rm_service_connection: '${{ variables.RM_SERVICE_CONNECTION }}'
          workspace: '${{ variables.WORKSPACE }}'
          resource_group: '${{ variables.RESOURCE_GROUP }}'
          aks_cluster: '${{ variables.AKS_CLUSTER }}'