parameters:
  service-name: ''
  postman-collection-file: ''
  rm-service-connection: ''
  workspace-name: ''
  resource-group: ''

jobs:
  - job: RunNewmanTests

    variables:
      newman_test_dir: '$(System.DefaultWorkingDirectory)/newman_tests'
    steps:
      - task: AzureCLI@2
        displayName: 'Install the CLI'
        inputs:
          scriptType: bash
          azureSubscription: ${{ parameters['rm-service-connection'] }}
          scriptLocation: inlineScript
          inlineScript: 'az extension add -n azure-cli-ml'

      - task: AzureCLI@2
        displayName: 'Look up API Key and Service Endpoint'
        inputs:
          scriptType: bash
          azureSubscription: ${{ parameters['rm-service-connection'] }}
          scriptLocation: inlineScript
          inlineScript: |
            az ml service get-keys --resource-group ${{ parameters['resource-group'] }} --workspace-name ${{ parameters['workspace-name'] }} -n  ${{ parameters['service-name'] }} --query "primaryKey" | xargs echo "##vso[task.setvariable variable=TMP_API_KEY]"
            az ml service show --resource-group ${{ parameters['resource-group'] }} --workspace-name ${{ parameters['workspace-name'] }} -n  ${{ parameters['service-name'] }} --query "scoringUri" | xargs echo "##vso[task.setvariable variable=TMP_SCORING_URI]"
            az ml service show --resource-group ${{ parameters['resource-group'] }} --workspace-name ${{ parameters['workspace-name'] }} -n  ${{ parameters['service-name'] }} --query "computeType" | xargs echo "##vso[task.setvariable variable=TMP_SERVICE_TYPE]"

      - task: ShellScript@2
        displayName: Install newman
        inputs:
          scriptPath: models/utils/test/install_newman.sh
          cwd: $(Build.SourcesDirectory)

      - bash: |
          mkdir $(newman_test_dir)
          newman run ${{ parameters['postman-collection-file'] }}  --global-var host="$(TMP_SCORING_URI)" --global-var api_key="$(TMP_API_KEY)" -r cli,junit --reporter-junit-export  $(newman_test_dir)
        displayName: "Run tests"
        workingDirectory: $(Build.SourcesDirectory)

      - task: PublishTestResults@2
        inputs:
          testResultsFormat: 'JUnit'
          testResultsFiles: '*.xml'
          searchFolder:  $(newman_test_dir)
